// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIhaZflHtWungzsw2OJVxenttIclICm8g',
    appId: '1:767444721120:web:059eecdcb6759ce6ea9f85',
    messagingSenderId: '767444721120',
    projectId: 'pruebapersona-ef145',
    authDomain: 'pruebapersona-ef145.firebaseapp.com',
    storageBucket: 'pruebapersona-ef145.firebasestorage.app',
    measurementId: 'G-4FPQZSWK96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7jed5C3GFd9UvzIziHVBBkBPaBCYZNeE',
    appId: '1:767444721120:android:26bb314d4cd55edaea9f85',
    messagingSenderId: '767444721120',
    projectId: 'pruebapersona-ef145',
    storageBucket: 'pruebapersona-ef145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ruedUSATZGILBLnHJR5QOFXvux2SweU',
    appId: '1:767444721120:ios:4538cdf5d6bb3494ea9f85',
    messagingSenderId: '767444721120',
    projectId: 'pruebapersona-ef145',
    storageBucket: 'pruebapersona-ef145.firebasestorage.app',
    iosClientId: '767444721120-tg2375hn6lf6mh1gc44o1kr48rkfhboe.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthAndFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ruedUSATZGILBLnHJR5QOFXvux2SweU',
    appId: '1:767444721120:ios:4538cdf5d6bb3494ea9f85',
    messagingSenderId: '767444721120',
    projectId: 'pruebapersona-ef145',
    storageBucket: 'pruebapersona-ef145.firebasestorage.app',
    iosClientId: '767444721120-tg2375hn6lf6mh1gc44o1kr48rkfhboe.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthAndFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIhaZflHtWungzsw2OJVxenttIclICm8g',
    appId: '1:767444721120:web:59fdbbe1d1320af5ea9f85',
    messagingSenderId: '767444721120',
    projectId: 'pruebapersona-ef145',
    authDomain: 'pruebapersona-ef145.firebaseapp.com',
    storageBucket: 'pruebapersona-ef145.firebasestorage.app',
    measurementId: 'G-EWFZS62R4W',
  );
}
